### ISSUE TITLE
Iterate by value?

### ISSUE THREAD

**Issue by pr0g** [Reedbeta/nrr_enumerate#3]
Hello there,

This is more of a question than an issue but after playing around with `nrr::enumerate` I've found that it currently isn't possible to use value semantics while iterating a collection. This gives subtly different behaviour from the `std::vector<std::tuple<ThingA, ThingB>>` example from the accompanying blog post.

For example, if we do this:

``` c++
std::vector<std::pair<int, int>> pairs(10);
for (auto [first, second] : pairs) {
    first++;
    second++;
}

for (const auto& p : pairs) {
    std::cout << p.first << ' ' << p.second << '\n';
}
```

Then `first` and `second` are copies, and the `++` operator will not modify the values in the vector. We'll get a bunch of `0`s printed.

If instead we write:

```c++
std::vector<std::pair<int, int>> pairs(10);
for (auto& [first, second] : pairs) { // note auto& here
    first++;
    second++;
}

for (const auto& p : pairs) {
    std::cout << p.first << ' ' << p.second << '\n';
}
```

Then `1`s will be printed instead as we're modifying the value by reference.

When using `enumerate` and not using `auto&` the underlying value is still actually a reference and can be modified in-place through the `iterator` type. Using `auto&` doesn't compile as we can't bind to a temporary, though `const auto&` does work due to lifetime extension (but of course you can still actually modify it because of the blasted logical vs physical `const` problem 🙈).

I realize 99% of the time you do want reference semantics and don't want to pay for a copy on every iteration of the loop but it's just a little confusing that it's not consistent with the normal behaviour or `auto` vs `auto&`. I also realize you can use `cenumerate` to work around the `const` issue but it's not ideal (I know most of this is C++'s fault and there isn't much we can do about it 😞).

I'm not sure if there is even a practical way to work around it but wanted to mention it in case you've given it any thought.

Thanks for your time,

Tom

**Comment by pr0g** [comment]
Here's a little wandbox example to try help explain what I mean - https://wandbox.org/permlink/KOKwfmGHMzsCkD9h

**Comment by Reedbeta** [comment]
Yeah, this is actually something I was experimenting with a few weeks ago. It's annoying to need to have `cenumerate` because declaring the iteration variables as `const auto` or `const auto&` doesn't do the expected thing.

This stems from how the type deduction works for structured bindings. When you write something like `const auto& [i, thing]`, the `const auto&` applies to the hidden tuple object that's returned from dereferencing the iterator produced by `enumerate`. But the constness or reference-ness of that object doesn't propagate to the constness or reference-ness of the tuple elements. So you end up getting a const reference to a `std::tuple<const int&, Thing&>` which doesn't help you.

I think a possible fix for this would be to replace the use of `std::tuple` with a custom pair type that would propagate its own constness and reference-ness to that of the second element, via overloaded `get` methods. I'd have to introduce specializations of `std::tuple_size` and `std::tuple_element` to [make it compatible with structured bindings](https://en.cppreference.com/w/cpp/language/structured_binding#Case_2:_binding_a_tuple-like_type). 

Another wrinkle is that `auto&` deduction won't work if the custom pair type is a temporary returned from the iterator's `operator *`. We would need to store the pair type inside the iterator and return a reference to it.

So, it would be a bunch of extra machinery, and I'm not sure it's actually possible to plumb it all the way through so that all cases work as expected. Would be kind of interesting to see how far you could get, though.

Somewhat relatedly, you currently can't enumerate ranges where `*iter` returns a temporary object (like `std::vector<bool>`, or `std::ranges::views::transform` and friends), since `enumerate` tries to take an lvalue reference to it. So another improvement for the custom pair object would be to handle capturing rvalues properly.

It would be interesting to look at how [range-v3](https://ericniebler.github.io/range-v3/) handles these problems, but its code has got so many layers that it's very difficult to decipher.

**Comment by pr0g** [comment]
Thanks for the information, I totally agree it is all a bit of a pain and there doesn't appear to be a silver bullet, unfortunately.

I got a much better handle on structured bindings by playing around with them in [CppInsights](https://cppinsights.io/). Here it's possible to see what's going on under the hood for a simple struct type:

```c++
struct thing_t {int a; int b;} thing;

auto [a_value, b_value] = thing;
// becomes...
thing_t __thing9 = thing_t(thing); // copy
int& a_value = __thing9.a;
int& b_value = __thing9.b;

auto& [a_ref, b_ref] = thing;
// becomes
thing_t& __thing10 = thing; // reference
int& a_ref = __thing10.a;
int& b_ref = __thing10.b;
```

Repeated [here](https://cppinsights.io/s/981cb40a)

The idea of a custom pair type might be interesting, it could potentially internally make use of the experimental [propagate_const](https://en.cppreference.com/w/cpp/experimental/propagate_const) to work around the logical/physical `const` issue.

I suppose in the meantime it might be worth calling out that `enumerate` does behave a little differently from how people might expect (perhaps in a code comment or in the README? Known Issues?). It just a pain the behaviour can be a little surprising given how useful having this is.

Cheers,


Tom
